#!/usr/bin/env sh

log() { printf "%s\n" "$@"; }

invalid() { printf "Invalid option: %s\n" "$*"; }

check_cmd() {
    if ! command -v "$1" >/dev/null; then
        log "Missing '$1'!"
        return 1
    fi
}

check_air() {
    if ! command -v air >/dev/null; then
        log "Missing 'air'! Install it with 'go get -u github.com/cosmtrek/air'"
        exit
    fi
}

check_dir() {
    pwd="$(pwd)"
    cd "${pwd%/tools}"
}

dev() {
    log "dev"
    check_air
    check_dir
    env DISCORD_AUTH=$(cat ./.auth) \
        air
}

case "$1" in
    dev)  dev  "$@" ;;
    *) invalid "$@" ;;
esac
